//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elp87.Finance.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("elp87.Finance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний убыток.
        /// </summary>
        internal static string prop_AvgLoseProfit {
            get {
                return ResourceManager.GetString("prop_AvgLoseProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний убыток %.
        /// </summary>
        internal static string prop_AvgLoseProfitPC {
            get {
                return ResourceManager.GetString("prop_AvgLoseProfitPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний П/У.
        /// </summary>
        internal static string prop_AvgProfit {
            get {
                return ResourceManager.GetString("prop_AvgProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний П/У.
        /// </summary>
        internal static string prop_AvgProfitPC {
            get {
                return ResourceManager.GetString("prop_AvgProfitPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя прибыль.
        /// </summary>
        internal static string prop_AvgWinProfit {
            get {
                return ResourceManager.GetString("prop_AvgWinProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя прибыль %.
        /// </summary>
        internal static string prop_AvgWinProfitPC {
            get {
                return ResourceManager.GetString("prop_AvgWinProfitPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чистый П/У.
        /// </summary>
        internal static string prop_ClearProfit {
            get {
                return ResourceManager.GetString("prop_ClearProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чистый П/У %.
        /// </summary>
        internal static string prop_ClearProfitPC {
            get {
                return ResourceManager.GetString("prop_ClearProfitPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общий убыток.
        /// </summary>
        internal static string prop_LoseProfitSum {
            get {
                return ResourceManager.GetString("prop_LoseProfitSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убыточных сделок.
        /// </summary>
        internal static string prop_LoseTradeCount {
            get {
                return ResourceManager.GetString("prop_LoseTradeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убыточных сделок %.
        /// </summary>
        internal static string prop_LoseTradeCountPC {
            get {
                return ResourceManager.GetString("prop_LoseTradeCountPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная просадка.
        /// </summary>
        internal static string prop_MaxDD {
            get {
                return ResourceManager.GetString("prop_MaxDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата макс.просадки.
        /// </summary>
        internal static string prop_MaxDDDate {
            get {
                return ResourceManager.GetString("prop_MaxDDDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная просадка %.
        /// </summary>
        internal static string prop_MaxDDPC {
            get {
                return ResourceManager.GetString("prop_MaxDDPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимум убыточных подряд.
        /// </summary>
        internal static string prop_MaxLoseRow {
            get {
                return ResourceManager.GetString("prop_MaxLoseRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимум прибыльных подряд.
        /// </summary>
        internal static string prop_MaxWinRow {
            get {
                return ResourceManager.GetString("prop_MaxWinRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доходность в месяц.
        /// </summary>
        internal static string prop_MonthProfit {
            get {
                return ResourceManager.GetString("prop_MonthProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коэффициент восстановления.
        /// </summary>
        internal static string prop_PayoffRatio {
            get {
                return ResourceManager.GetString("prop_PayoffRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профит-фактор.
        /// </summary>
        internal static string prop_ProfitFactor {
            get {
                return ResourceManager.GetString("prop_ProfitFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактор восстановления.
        /// </summary>
        internal static string prop_RecoveryFactor {
            get {
                return ResourceManager.GetString("prop_RecoveryFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество сделок.
        /// </summary>
        internal static string prop_TradeCount {
            get {
                return ResourceManager.GetString("prop_TradeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая прибыль.
        /// </summary>
        internal static string prop_WinProfitSum {
            get {
                return ResourceManager.GetString("prop_WinProfitSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыльных сделок.
        /// </summary>
        internal static string prop_WinTradeCount {
            get {
                return ResourceManager.GetString("prop_WinTradeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыльных сделок %.
        /// </summary>
        internal static string prop_WinTradeCountPC {
            get {
                return ResourceManager.GetString("prop_WinTradeCountPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доходность в год.
        /// </summary>
        internal static string prop_YearProfit {
            get {
                return ResourceManager.GetString("prop_YearProfit", resourceCulture);
            }
        }
    }
}
